#!/bin/bash
#
# Generate GRAMMARS.md from grammars.yaml.
#
# Usage: generate-grammars-md.sh [--check]
#
# Without arguments, regenerates GRAMMARS.md.
# With --check, exits non-zero if GRAMMARS.md is out of date.

set -uo pipefail

SCRIPT_DIR=$(dirname "$0")
REPO_ROOT=$(realpath "$SCRIPT_DIR/..")
REGISTRY="$REPO_ROOT/grammars.yaml"
OUTPUT="$REPO_ROOT/GRAMMARS.md"

CHECK=false
AUTOFIX=false
case "${1:-}" in
    --check) CHECK=true ;;
    --autofix) CHECK=true; AUTOFIX=true ;;
esac

generate() {
    python3 -c "
import yaml

with open('$REGISTRY') as f:
    grammars = yaml.safe_load(f)

lines = [
    '<!-- This file is auto-generated by scripts/generate-grammars-md.sh -->',
    '',
    '# Grammar Inventory',
    '',
    '| Language | Parser | Scanner | Highlights | Locals | Injections | Folds | Indents | Tags | ABI |',
    '|----------|--------|---------|------------|--------|------------|-------|---------|------|-----|',
]

Y = ':white_check_mark:'
N = ':x:'

def check(val):
    return Y if val else N

for g in grammars:
    m = g.get('metadata', {})
    enabled = g.get('enabled', True)
    url = g['url']
    ref = g.get('ref', '')
    lang = g['language']

    lang_link = f'[{lang}]({url}/tree/{ref})'
    if not enabled:
        lang_link = f'~~{lang_link}~~'

    queries_only = not m.get('hasParser') and not m.get('hasScanner')
    abi = 'N/A' if queries_only else m.get('abi', '-')

    row = (
        f'| {lang_link} '
        f'| {check(m.get(\"hasParser\"))} '
        f'| {check(m.get(\"hasScanner\"))} '
        f'| {check(m.get(\"hasHighlights\"))} '
        f'| {check(m.get(\"hasLocals\"))} '
        f'| {check(m.get(\"hasInjections\"))} '
        f'| {check(m.get(\"hasFolds\"))} '
        f'| {check(m.get(\"hasIndents\"))} '
        f'| {check(m.get(\"hasTags\"))} '
        f'| {abi} |'
    )
    lines.append(row)

enabled = [g for g in grammars if g.get('enabled', True)]
disabled = [g for g in grammars if not g.get('enabled', True)]
unique_langs = set(g['language'] for g in enabled)
nvim_queries = sum(1 for g in enabled
    if not g.get('metadata', {}).get('hasParser')
    and not g.get('metadata', {}).get('hasScanner')
    and 'nvim-treesitter' in g.get('url', ''))
has_hl = len(set(g['language'] for g in enabled if g.get('metadata', {}).get('hasHighlights')))

lines.append('')
lines.append('| Metric | Count |')
lines.append('|--------|-------|')
lines.append(f'| Total entries | {len(grammars)} |')
lines.append(f'| Enabled | {len(enabled)} |')
lines.append(f'| Disabled | {len(disabled)} |')
lines.append(f'| Unique languages | {len(unique_langs)} |')
lines.append(f'| With highlights | {has_hl} |')
lines.append(f'| Queries from [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) | {nvim_queries} |')

print('\n'.join(lines))
"
}

if $CHECK; then
    if [ -f "$OUTPUT" ] && diff -q <(generate) "$OUTPUT" >/dev/null 2>&1; then
        echo 'GRAMMARS.md is up to date.'
        exit 0
    elif $AUTOFIX; then
        generate > "$OUTPUT"
        echo "GRAMMARS.md was out of date. Fixed."
        exit 0
    else
        echo 'GRAMMARS.md is out of date. Run: scripts/generate-grammars-md.sh'
        exit 1
    fi
else
    generate > "$OUTPUT"
    echo "Generated $OUTPUT"
fi
